const ERROR_MESSAGE = {
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
    USER_REGISTERED_SUCCESSFULLY: 'USER_REGISTERED_SUCCESSFULLY',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    EMAIL_REQUIRED: 'EMAIL_REQUIRED',
    PASSWORD_REQUIRED: 'PASSWORD_REQUIRED',

    DUPLICATE_VALUE: 'DUPLICATE_VALUE',
    INPUT_MISSING: 'INPUT_MISSING',
    INVALID_ROLE: 'INVALID_ROLE',
    NAME_REQUIRED: 'NAME_REQUIRED',
    MOB_NUMBER_REQUIRED: 'MOB_NUMBER_REQUIRED',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    UNAUTHORIZED_ROLE: 'UNAUTHORIZED_ROLE',


    UNAUTHORIZED: 'UNAUTHORIZED',
    NOT_FOUND: 'NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    SERVER_ERROR: 'SERVER_ERROR',


    LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
    DATABASE_ERROR: 'DATABASE_ERROR',
}

module.exports = ERROR_MESSAGE;
